Minor README edits (#21)
* Minor README edits

* Don't install jazzy on xenial

Ruby is too old:

```
ERROR:  Error installing jazzy:
	cocoapods-downloader requires Ruby version >= 2.3.3.
```